---
title: "decomp_sims"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(arm)
```

I'm following Raggi et al.


### functions for decomposition

the $g$ function

```{r}
g.fun <- function(xx,yy, beta_00, beta_xx, beta_ww, gamma_00, gamma_xx){
  
  yy*(beta_ww) + #+beta_xw if there was an interaction 
    log((1 +  exp(beta_00 + beta_xx * xx))/
          (1 + exp(beta_00 + beta_xx * xx + beta_ww))) + #+beta_xw if there was an interaction 
    gamma_00 + gamma_xx * xx
}

#g.fun evaluated at beta_xx=0
g.fun.star <-function(xx,yy, beta_00, beta_ww, gamma_00, gamma_xx){
  yy*(beta_ww) + #+beta_xw if there was an interaction 
    log((1 +  exp(beta_00))/
          (1 + exp(beta_00 + beta_ww))) + #+beta_xw if there was an interaction 
    gamma_00 + gamma_xx * xx
}

```


### parameter values
```{r}
p.x <- 0.1 #prevalence of x

##x-w relationship

#gamma_0 = log(p/(1-p)) where p is the probability of having a gun 
#for white people 
#I'm setting this at 0.1
p.x0 <- 0.5
gamma_0 <- logit(p.x0)

# black people are more likely to have a gun than white people
# let's say a plausible set of values would be 0-3 times more likely
p.x1w1 <- 0.7
gamma_x <- logit(p.x1w1) - gamma_0
                 

###x,w,y relationship
#beta_0 is for white people who don't have guns
#beta_0= log(p.x0w0/(1-p.x0w0))
p.x0w0 <- 0.55
beta_0 <- logit(p.x0w0)

#beta_x is the direct effect. For now we set it at 0
beta_x <- 0

#beta_w is added value of having a gun
#we assume this does not depend on the race
#let's assume that the chance of imprisonment increases
#by a factor of 0-2
p.w1 <- 0.65
beta_w <- logit(p.w1) - beta_0 


#no interactions
#no confounders/covariates
```


### generate x, w and y

```{r}
n.reps <- 100

test<-data.frame(keep.py=0,TE_glm=0, TE_x_OR=0, TE_x=0, IE_x=0, DE_x=0, RES_x=0)

for(ii in 1:n.reps){

n.samp <- 1000

keep.py=TE_glm=TE_x_OR=TE_x=IE_x=DE_x=RES_x=NA

MoJ = tibble(x = rbinom(n.samp, 1, p.x)) %>%   #proportion of black offenders.
      mutate(p_w = invlogit(gamma_0 + gamma_x * x)) %>%
      mutate(w =rbinom(n.samp, size=1, prob=p_w)) %>% 
      mutate(p_y =invlogit(beta_0 + beta_x * x + beta_w * w)) %>%
      mutate(y=rbinom(n=n.samp, size=1, prob=p_y))

#x <- rbinom(n.samp, 1, p.x)
#p_w <- invlogit(gamma_0 + gamma_x * x)
#w <- rbinom(n=n.samp, size=1, p_w)
#p_y <- invlogit(beta_0 + beta_x * x + beta_w * w)
#y <- rbinom(n=n.samp, size=1, p_y)
#MoJ <- data.frame(x=x,w=w,y=y)
      
#constraint 1: p(y)=0.55
keep.py <- (sum(MoJ$y)/n.samp)

#constraint 2: TE/NAIVE OR betwee 1.5-1.6
TE_glm<-exp(glm(y ~ x, data=MoJ, family=binomial)$coef[2])

### discrete x: TE, IE, DE and RES
beta_est <- glm(y ~ x * w, data=MoJ, family = binomial)$coef
gamma_est <- glm(w ~ x, data=MoJ, family=binomial)$coef

#TE calculated the Raggi way
TE_x <- beta_est[2] + 
  log((1 + exp(g.fun(1,1,beta_00 = beta_est[1], beta_xx=beta_est[2], beta_ww=beta_est[3], gamma_00=gamma_est[1], gamma_xx = gamma_est[2])))/(1+exp(g.fun(0,1,beta_00 = beta_est[1], beta_xx=beta_est[2], beta_ww=beta_est[3],gamma_00=gamma_est[1], gamma_xx = gamma_est[2])))) - 
  log((1 + exp(g.fun(1,0,beta_00 = beta_est[1], beta_xx=beta_est[2], beta_ww=beta_est[3],gamma_00=gamma_est[1], gamma_xx = gamma_est[2])))/(1+exp(g.fun(0,0,beta_00 = beta_est[1], beta_xx=beta_est[2], beta_ww=beta_est[3],gamma_00=gamma_est[1], gamma_xx = gamma_est[2]))))

TE_x_OR <- exp(TE_x)

#IE calculated the Raggi way
IE_x <- log((1 + exp(g.fun.star(1,1,beta_00 = beta_est[1], beta_ww=beta_est[3],gamma_00=gamma_est[1], gamma_xx = gamma_est[2])))/(1+exp(g.fun.star(0,1,beta_00 = beta_est[1], beta_ww=beta_est[3],gamma_00=gamma_est[1], gamma_xx = gamma_est[2])))) - 
  log((1 + exp(g.fun(1,0,beta_00 = beta_est[1], beta_xx=beta_est[2], beta_ww=beta_est[3],gamma_00=gamma_est[1], gamma_xx = gamma_est[2])))/(1+exp(g.fun(0,0,beta_00 = beta_est[1], beta_xx=beta_est[2], beta_ww=beta_est[3],gamma_00=gamma_est[1], gamma_xx = gamma_est[2]))))

#DE calculated the Raggi way 
DE_x <- beta_est[2]

#RES caluclated the Raggi way
RES_x <- TE_x - DE_x - IE_x 

internal<-data.frame(keep.py=keep.py,TE_glm=TE_glm, TE_x_OR=TE_x_OR, TE_x=TE_x, IE_x=IE_x, DE_x=DE_x, RES_x=RES_x)
#internal <- c(keep.py, TE_glm, TE_x_OR, TE_x, IE_x, DE_x, RES_x)
test <- rbind(test, internal)
}
test<-test[-1,]
apply(test, 2, mean)
apply(test, 2, sd)
```